### ISSUE TITLE
Setup Fails

### ISSUE THREAD

**Issue by ewmccarty** [formio/formio-webhook-receiver#3]
Link to this GitHub from https://help.form.io/developer/libraries/ is broken.

Setup Fails

C:\o\OB\R\Samples\formio-webhook-receiver>npm install
npm WARN package.json formio-webhook-receiver@1.0.0 No repository field.
npm WARN engine aws-serverless-express@3.3.6: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine dotenv@6.2.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine claudia@5.5.0: wanted: {"node":">=6.10.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine eslint@5.16.0: wanted: {"node":"^6.14.0 || ^8.10.0 || >=9.10.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine mime@1.6.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine https-proxy-agent@2.2.1: wanted: {"node":">= 4.5.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine archiver@2.1.1: wanted: {"node":">= 4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine agent-base@4.2.1: wanted: {"node":">= 4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine universalify@0.1.2: wanted: {"node":">= 4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine cross-spawn@6.0.5: wanted: {"node":">=4.8"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine chalk@2.4.2: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine eslint-scope@4.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine strip-ansi@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine import-fresh@3.0.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine eslint-visitor-keys@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine file-entry-cache@5.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine doctrine@3.0.0: wanted: {"node":">=6.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine globals@11.12.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine inquirer@6.3.1: wanted: {"node":">=6.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine table@5.3.3: wanted: {"node":">=6.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ignore@4.0.6: wanted: {"node":">= 4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine espree@5.0.1: wanted: {"node":">=6.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine eslint-utils@1.3.1: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine regexpp@2.0.1: wanted: {"node":">=6.5.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-regex@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine parent-module@1.0.1: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine resolve-from@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-styles@3.2.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine supports-color@5.5.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine flat-cache@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine esrecurse@4.2.1: wanted: {"node":">=4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine has-flag@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine callsites@3.1.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine write@1.0.3: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine strip-ansi@5.2.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine string-width@2.1.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-escapes@3.2.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine cli-cursor@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine external-editor@3.0.3: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine figures@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine string-width@3.1.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine slice-ansi@2.1.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine esprima@4.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine strip-ansi@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-regex@4.1.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine restore-cursor@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine strip-ansi@5.2.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-styles@3.2.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine astral-regex@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-regex@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine ansi-regex@4.1.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine onetime@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine mimic-fn@1.2.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine xmlbuilder@9.0.7: wanted: {"node":">=4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
dotenv@6.2.0 node_modules\dotenv

eslint-config-formio@1.1.4 node_modules\eslint-config-formio

basic-auth@2.0.1 node_modules\basic-auth
└── safe-buffer@5.1.2

method-override@3.0.0 node_modules\method-override
├── methods@1.1.2
├── parseurl@1.3.3
├── vary@1.1.2
└── debug@3.1.0 (ms@2.0.0)

aws-serverless-express@3.3.6 node_modules\aws-serverless-express
├── binary-case@1.1.4
└── type-is@1.6.18 (media-typer@0.3.0, mime-types@2.1.24)

express@4.17.0 node_modules\express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── methods@1.1.2
├── cookie-signature@1.0.6
├── utils-merge@1.0.1
├── merge-descriptors@1.0.1
├── vary@1.1.2
├── parseurl@1.3.3
├── path-to-regexp@0.1.7
├── content-type@1.0.4
├── setprototypeof@1.1.1
├── range-parser@1.2.1
├── encodeurl@1.0.2
├── fresh@0.5.2
├── etag@1.8.1
├── statuses@1.5.0
├── cookie@0.4.0
├── content-disposition@0.5.3
├── serve-static@1.14.1
├── safe-buffer@5.1.2
├── depd@1.1.2
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@1.1.2 (unpipe@1.0.0)
├── debug@2.6.9 (ms@2.0.0)
├── proxy-addr@2.0.5 (forwarded@0.1.2, ipaddr.js@1.9.0)
├── qs@6.7.0
├── send@0.17.1 (ms@2.1.1, destroy@1.0.4, http-errors@1.7.2, mime@1.6.0)
├── type-is@1.6.18 (media-typer@0.3.0, mime-types@2.1.24)
└── accepts@1.3.7 (negotiator@0.6.2, mime-types@2.1.24)

body-parser@1.19.0 node_modules\body-parser
├── content-type@1.0.4
├── bytes@3.1.0
├── depd@1.1.2
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.7.2 (toidentifier@1.0.0, inherits@2.0.3, setprototypeof@1.1.1, statuses@1.5.0)
├── raw-body@2.4.0 (unpipe@1.0.0)
├── debug@2.6.9 (ms@2.0.0)
├── qs@6.7.0
├── type-is@1.6.18 (media-typer@0.3.0, mime-types@2.1.24)
└── iconv-lite@0.4.24 (safer-buffer@2.1.2)

lodash@4.17.11 node_modules\lodash

claudia@5.5.0 node_modules\claudia
├── minimal-request-promise@1.5.0
├── sequential-promise-map@1.1.0
├── oh-no-i-insist@1.1.1
├── minimist@1.2.0
├── uuid@2.0.3
├── which@1.3.1 (isexe@2.0.0)
├── glob@7.1.4 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.4)
├── fs-extra@6.0.1 (universalify@0.1.2, jsonfile@4.0.0, graceful-fs@4.1.15)
├── tar-fs@1.16.3 (chownr@1.1.1, pump@1.0.3, mkdirp@0.5.1, tar-stream@1.6.2)
├── https-proxy-agent@2.2.1 (debug@3.2.6, agent-base@4.2.1)
├── gunzip-maybe@1.4.1 (is-gzip@1.0.0, is-deflate@1.0.0, through2@2.0.5, peek-stream@1.1.3, pumpify@1.5.1, browserify-zlib@0.1.4)
├── archiver@2.1.1 (buffer-crc32@0.2.13, archiver-utils@1.3.0, tar-stream@1.6.2, readable-stream@2.3.6, async@2.6.2, zip-stream@1.2.0)
└── aws-sdk@2.460.0 (ieee754@1.1.8, sax@1.2.1, querystring@0.2.0, uuid@3.3.2, events@1.1.1, url@0.10.3, jmespath@0.15.0, xml2js@0.4.19, buffer@4.9.1)

eslint@5.16.0 node_modules\eslint
├── path-is-inside@1.0.2
├── natural-compare@1.4.0
├── strip-json-comments@2.0.1
├── imurmurhash@0.1.4
├── progress@2.0.3
├── eslint-visitor-keys@1.0.0
├── globals@11.12.0
├── ignore@4.0.6
├── functional-red-black-tree@1.0.1
├── text-table@0.2.0
├── json-stable-stringify-without-jsonify@1.0.1
├── esutils@2.0.2
├── strip-ansi@4.0.0 (ansi-regex@3.0.0)
├── semver@5.7.0
├── doctrine@3.0.0
├── minimatch@3.0.4 (brace-expansion@1.1.11)
├── glob@7.1.4 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0)
├── debug@4.1.1 (ms@2.1.1)
├── import-fresh@3.0.0 (resolve-from@4.0.0, parent-module@1.0.1)
├── esquery@1.0.1 (estraverse@4.2.0)
├── levn@0.3.0 (type-check@0.3.2, prelude-ls@1.1.2)
├── cross-spawn@6.0.5 (path-key@2.0.1, nice-try@1.0.5, shebang-command@1.2.0, which@1.3.1)
├── eslint-scope@4.0.3 (esrecurse@4.2.1, estraverse@4.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optionator@0.8.2 (fast-levenshtein@2.0.6, type-check@0.3.2, deep-is@0.1.3, prelude-ls@1.1.2, wordwrap@1.0.0)
├── @babel/code-frame@7.0.0 (@babel/highlight@7.0.0)
├── eslint-utils@1.3.1
├── chalk@2.4.2 (escape-string-regexp@1.0.5, supports-color@5.5.0, ansi-styles@3.2.1)
├── file-entry-cache@5.0.1 (flat-cache@2.0.1)
├── table@5.3.3 (string-width@3.1.0, slice-ansi@2.1.0)
├── regexpp@2.0.1
├── espree@5.0.1 (acorn-jsx@5.0.1, acorn@6.1.1)
├── js-yaml@3.13.1 (esprima@4.0.1, argparse@1.0.10)
├── ajv@6.10.0 (fast-deep-equal@2.0.1, json-schema-traverse@0.4.1, fast-json-stable-stringify@2.0.0, uri-js@4.2.2)
└── inquirer@6.3.1 (ansi-escapes@3.2.0, cli-width@2.2.0, through@2.3.8, figures@2.0.0, strip-ansi@5.2.0, run-async@2.3.0, string-width@2.1.1, mute-stream@0.0.7, cli-cursor@2.1.0, external-editor@3.0.3, rxjs@6.5.2)

C:\o\OB\R\Samples\formio-webhook-receiver>npm run start:basic

> formio-webhook-receiver@1.0.0 start:basic C:\o\OB\R\Samples\formio-webhook-receiver
> node basic

C:\o\OB\R\Samples\formio-webhook-receiver\basic\index.js:5
const app = require('./server');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start:basic"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! formio-webhook-receiver@1.0.0 start:basic: `node basic`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio-webhook-receiver@1.0.0 start:basic script 'node basic'.
npm ERR! This is most likely a problem with the formio-webhook-receiver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node basic
npm ERR! You can get their info via:
npm ERR!     npm owner ls formio-webhook-receiver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\o\OB\R\Samples\formio-webhook-receiver\npm-debug.log

C:\o\OB\R\Samples\formio-webhook-receiver>npm run start:validation

> formio-webhook-receiver@1.0.0 start:validation C:\o\OB\R\Samples\formio-webhook-receiver
> node validation

C:\o\OB\R\Samples\formio-webhook-receiver\validation\index.js:5
const app = require('./server');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start:validation"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! formio-webhook-receiver@1.0.0 start:validation: `node validation`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio-webhook-receiver@1.0.0 start:validation script 'node validation'.
npm ERR! This is most likely a problem with the formio-webhook-receiver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node validation
npm ERR! You can get their info via:
npm ERR!     npm owner ls formio-webhook-receiver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\o\OB\R\Samples\formio-webhook-receiver\npm-debug.log

C:\o\OB\R\Samples\formio-webhook-receiver>npm owner ls formio-webhook-receiver
npm ERR! owner ls Couldn't get owner data formio-webhook-receiver
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "owner" "ls" "formio-webhook-receiver"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E404

npm ERR! 404 Not found : formio-webhook-receiver
npm ERR! 404
npm ERR! 404 'formio-webhook-receiver' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\o\OB\R\Samples\formio-webhook-receiver\npm-debug.log

C:\o\OB\R\Samples\formio-webhook-receiver>

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
